### ISSUE TITLE
Fails to build with 8.4

### ISSUE THREAD

**Issue by dminuoso** [Yuras/pdf-toolbox#35]
Toolbox fails to build with 8.4 because of the SMP
```
lib/Pdf/Core/Name.hs:24:28: error:
    • No instance for (Semigroup Name)
        arising from the 'deriving' clause of a data type declaration
      Possible fix:
        use a standalone 'deriving instance' declaration,
          so you can specify the instance context yourself
    • When deriving the instance for (Monoid Name)
   |
24 |   deriving (Eq, Show, Ord, Monoid, Hashable)
   |                            ^^^^^^
```

A fix is already in #34 

This issue is just for documentation.

**Comment by Yuras** [comment]
Sorry for the delay. I enabled ghc-8.4 in CI and fixed the build, see #37 
Though I was not able to really test it, I don't have ghc-8.4 locally yet. So it would be awesome if you try it out.
