### ISSUE TITLE
latest hackage's release fails to build on ghc-8.8: lib/Pdf/Toolbox/Content/UnicodeCMap.hs:190:5: error:     • Could not deduce (MonadFail m) arising from a use of ‘fail’

### ISSUE THREAD

**Issue by trofi** [Yuras/pdf-toolbox#63]
```
Building library for pdf-toolbox-content-0.0.5.1..
[ 1 of 12] Compiling Prelude          ( compat/Prelude.hs, dist/build/Prelude.o )
[ 2 of 12] Compiling Pdf.Toolbox.Content.UnicodeCMap ( lib/Pdf/Toolbox/Content/UnicodeCMap.hs, dist/build/Pdf/Toolbox/Content/UnicodeCMap.o )

lib/Pdf/Toolbox/Content/UnicodeCMap.hs:190:5: error:
    • Could not deduce (MonadFail m) arising from a use of ‘fail’
      from the context: Monad m
        bound by the type signature for:
                   fromHex :: forall (m :: * -> *).
                              Monad m =>
                              ByteString -> m ByteString
        at lib/Pdf/Toolbox/Content/UnicodeCMap.hs:186:1-48
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            fromHex :: forall (m :: * -> *).
                       Monad m =>
                       ByteString -> m ByteString
    • In the second argument of ‘($)’, namely
        ‘fail $ "Can't decode hex" ++ show rest’
      In a stmt of a 'do' block:
        unless (BS.null rest) $ fail $ "Can't decode hex" ++ show rest
      In the expression:
        do let (str, rest) = Base16.decode $ bsToLower hex
           unless (BS.null rest) $ fail $ "Can't decode hex" ++ show rest
           return str
    |
190 |     fail $ "Can't decode hex" ++ show rest
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

git repo seems to build fine. Worth cutting a new release?

**Comment by Yuras** [comment]
Yep, in #42 I promised to cut a release, but never actually did it, sorry. I won't promise anything this time, because I'm not sure when I'll have time for that.
Closing as a duplicate of #42
